INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (1, 'Системный блок MACUBE', '101344-3583', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (2, 'Системный блок MACUBE', '101344-3584', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (3, 'Системный блок MACUBE', '101344-3585', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (4, 'Системный блок MACUBE', '101344-3586', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (5, 'Системный блок MACUBE', '101344-3587', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (6, 'Системный блок MACUBE', '101344-3588', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (7, 'Системный блок MACUBE', '101344-3593', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (8, 'Системный блок MACUBE', '101344-3594', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (9, 'Системный блок MACUBE', '101344-3596', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (10, 'Монитор LG27UL500-W', '101344-3567', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (11, 'Монитор LG27UL500-W', '101344-3568', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (12, 'Монитор LG27UL500-W', '101344-3570', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (13, 'Монитор LG27UL500-W', '101344-3571', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (14, 'Монитор LG27UL500-W', '101344-3572', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (15, 'Монитор LG27UL500-W', '101344-3574', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (16, 'Монитор LG27UL500-W', '101344-3576', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (17, 'Монитор LG27UL500-W', '101344-3580', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (18, 'Монитор LG27UL500-W', '101344-3581', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (19, 'Монитор AOC 22B2QAM', '101344-3988', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (20, 'Монитор AOC 22B2QAM', '101344-3997', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (21, 'Монитор AOC 22B2QAM', '101344-4002', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (22, 'Монитор AOC 22B2QAM', '101344-4005', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (23, 'Монитор AOC 22B2QAM', '101344-4019', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (24, 'Монитор AOC 22B2QAM', '101344-4021', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (25, 'Монитор AOC 22B2QAM', '101344-4022', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (26, 'Монитор AOC 22B2QAM', '101344-4025', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (27, 'Монитор AOC 22B2QAM', '101344-4030', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (28, 'Монитор AOC 22B2QAM', '101344-4306', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (29, 'Монитор AOC 22B2QAM', '101344-4318', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (30, 'Монитор AOC 22B2QAM', '101344-4321', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (31, 'Системный блок IRU', '101344-4330', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (32, 'Системный блок IRU', '101344-4332', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (33, 'Системный блок IRU', '101344-4336', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (34, 'Системный блок IRU', '101344-4337', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (35, 'Системный блок IRU', '101344-4342', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (36, 'Системный блок IRU', '101344-4378', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (37, 'Системный блок IRU', '101344-4386', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (38, 'Системный блок IRU', '101344-4387', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (39, 'Системный блок IRU', '101344-4388', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (40, 'Системный блок IRU', '101344-4389', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (41, 'Системный блок IRU', '101344-4390', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (42, 'Системный блок IRU', '101344-4401', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (43, 'Монитор AOC 22B2QAM', '101344-3992', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (44, 'Монитор AOC 22B2QAM', '101344-3999', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (45, 'Монитор AOC 22B2QAM', '101344-4000', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (46, 'Монитор AOC 22B2QAM', '101344-4001', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (47, 'Монитор AOC 22B2QAM', '101344-4024', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (48, 'Монитор AOC 22B2QAM', '101344-4304', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (49, 'Монитор AOC 22B2QAM', '101344-4305', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (50, 'Монитор AOC 22B2QAM', '101344-4313', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (51, 'Системный блок IRU', '101344-4329', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (52, 'Системный блок IRU', '101344-4331', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (53, 'Системный блок IRU', '101344-4335', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (54, 'Системный блок IRU', '101344-4341', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (55, 'Системный блок IRU', '101344-4343', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (56, 'Системный блок IRU', '101344-4345', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (57, 'Системный блок IRU', '101344-4361', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (58, 'Системный блок IRU', '101344-4384', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (59, 'Монитор AOC E2275-SWJ', '101342-752-26', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (60, 'Монитор AOC E2275-SWJ', '101342-752-28', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (61, 'Монитор AOC E2275-SWJ', '101342-752-29', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (62, 'Монитор AOC E2275-SWJ', '101342-752-30', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (63, 'Монитор AOC E2275-SWJ', '101342-752-23', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (64, 'Монитор AOC E2275-SWJ', '101342-752-24', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (65, 'Монитор AOC E2275-SWJ', '101342-752-25', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (66, 'Системный блок NPC T310', '101344-431', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (67, 'Системный блок NPC T310', '101344-432', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (68, 'Системный блок NPC T310', '101344-433', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (69, 'Системный блок NPC T310', '101344-434', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (70, 'Системный блок NPC T310', '101344-435', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (71, 'Системный блок NPC T310', '101344-436', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (72, 'Системный блок NPC T310', '?', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (73, 'МБ', '101344-2907', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (74, 'Системный блок NPC T310', '101344-424', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (75, 'Системный блок NPC T310', '101344-420', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (76, 'Системный блок NPC T310', '101344-421', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (77, 'Системный блок NPC T310', '101344-419', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (78, 'Системный блок NPC T310', '101344-418', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (79, 'Системный блок NPC T310', '101344-423', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (80, 'Системный блок NPC T310', '101344-429', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (81, 'Системный блок NPC T310', '101344-428', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (82, 'Системный блок NPC T310', '101344-427', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (83, 'Системный блок NPC T310', '101344-426', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (84, 'Системный блок NPC T310', '101344-422', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (85, 'Системный блок NPC T310', '101344-2907', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (86, 'Монитор', '101041-1062', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (87, 'Монитор', '101041-1059', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (88, 'Монитор', '101041-1061', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (89, 'Монитор', '101041-1065', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (90, 'Монитор', '101041-1067', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (91, 'Монитор', '101041-1060', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (92, 'Монитор', '101041-1054', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (93, 'Монитор', '101041-1058', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (94, 'Монитор', '101041-1071', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (95, 'Монитор', '101041-1057', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (96, 'Монитор', '101041-1063', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (97, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-220', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (98, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-222', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (99, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-223', '35542', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (100, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-224', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (101, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-225', '22808', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (102, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-226', '23812', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (103, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-227', '23843', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (104, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-228', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (105, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-229', '23855', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (106, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-230', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (107, 'Брайлевский дисплей ElecGeste BD-40-001 PRO', '101043-233', '23782', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (108, 'Брайлевский дисплей FreedomScientific F40', '101244-6', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (109, 'Брайлевский дисплей FreedomScientific F41', '101244-5', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (110, 'Монитор AOC E2275-SWJ', '101342-752-14', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (111, 'Монитор AOC E2275-SWJ', '101342-752-15', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (112, 'Монитор AOC E2275-SWJ', '101342-752-16', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (113, 'Монитор AOC E2275-SWJ', '101342-752-17', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (114, 'Монитор AOC E2275-SWJ', '101342-752-18', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (115, 'Монитор AOC E2275-SWJ', '101342-752-19', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (116, 'Монитор AOC E2275-SWJ', '101342-752-20', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (117, 'Монитор AOC E2275-SWJ', '101342-753-3', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (118, 'Монитор AOC E2275-SWJ', '101342-753-5', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (119, 'Монитор AOC E2275-SWJ', '101342-753-6', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (120, 'Системный блок IRU', '101344-4398', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (121, 'Монитор AOC 22B2QAM', '101344-4029', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (122, 'Системный блок MACUBE', '101344-3582', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (123, 'Системный блок MACUBE', '101344-3589', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (124, 'Системный блок MACUBE', '101344-3590', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (125, 'Системный блок MACUBE', '101344-3591', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (126, 'Системный блок MACUBE', '101344-3592', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (127, 'Системный блок MACUBE', '101344-3595', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (128, 'Монитор LG27UL500-W', '101344-3569', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (129, 'Монитор LG27UL500-W', '101344-3573', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (130, 'Монитор LG27UL500-W', '101344-3575', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (131, 'Монитор LG27UL500-W', '101344-3577', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (132, 'Монитор LG27UL500-W', '101344-3578', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (133, 'Монитор LG27UL500-W', '101344-3579', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (134, 'Проектор InFocus IN126x', '101345-120', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (135, 'Проектор InFocus IN126x', '101345-118', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (136, 'Проектор NEC V260X', '?', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (137, 'Oldi', '101041-1055', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (138, 'Монитор LG W2242S', '101041-1073', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (139, 'Монитор AOC E2275-SWJ', '101342-753-4', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (140, 'Сканнер Cannon F910111', '101041-140', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (141, 'Сканнер Cannon F910111', '101041-144', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (142, 'Камера Phillips', '1040800903', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (143, 'Камера Phillips', '1040800904', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (144, 'Камера Phillips', '1040800905', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (145, 'Камера Phillips', '1040800906', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (146, 'Камера Phillips', '1040800907', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (147, 'Камера Phillips', '1040800908', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (148, 'Камера Phillips', '1040800909', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (149, 'Камера Phillips', '1040800910', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (150, 'Камера Phillips', '1040800911', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (151, 'Камера Phillips', '1040800912', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (152, 'Камера Phillips', '1040800913', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (153, 'Камера Phillips', '1040800914', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (154, 'Камера Phillips', '1040800916', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (155, 'Веб камера D-Link', '1380786', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (156, 'Веб камера D-Link', '1380787', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (157, 'Веб камера D-Link', '1380788', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (158, 'Электронный увеличитель', '101043-66', '23877', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (159, 'Электронный увеличитель', '101043-67', '23868', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (160, 'Настольная подставка для микрофона', '1040800882', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (161, 'Видеокомплект JVC', '1040800515', '33891', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (162, 'Lacie D2 HD 80GB', '1360646', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (163, 'Музыкальный центр Samsung MM-G25R', '101042-556', '34867', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (164, 'Акустическая система Sven SPS-721', '101344-2800', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (165, 'Акустическая система Sven SPS-721', '101344-2799', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (166, 'Акустическая система SVEN 2.0 SPS-700', '101041-1039', '33834', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (167, 'Графический планшет Беспроводной', '101041-1040', '33878', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (168, 'Принтер лазерный EPSON EPL-6200L', '101041-132', '23837', null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (169, 'Kraftway', '101041-953', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (170, 'Kraftway', '101041-954', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (171, 'Монитор Acer v193W', '101041-933', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (172, 'Монитор Acer v193W', '101041-932', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (173, 'Принтер Samsung Pro Express m3820ND', '101344-728', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (174, 'Kraftway', '101041-956', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (175, 'Принтер LaserJet P2055 DN', '101042-611', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (176, 'Монитор Acer v193W', '101041-935', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (177, 'Принтер Nashuatec MP1500', '101041-91', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (178, 'Kraftway', '101041-955', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (179, 'Монитор Acer v193W', '101041-934', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (180, 'Системный блок Oldi', '101041-1061', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (181, 'Принтер HP C7063A', '104060043', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (182, 'Монитор LG W2242S-BFH.AEUVQPC', '101041-72', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (183, 'Сканнер Cannon F134800', '1040600598', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (184, 'Kraftway', '101041-958', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (185, 'Принтер Acer v193W', '101041-931', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (186, 'Принтер HP LaserJet 1536dnf', '101041-1174', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (187, 'Kraftway', '101041-957', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (188, 'Принтер Acer v193W', '101041-986', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (189, 'Монитор LG W2242S-BFH.AEUVQPC', '101041-1068', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (190, 'Системный блок Oldi', '101041-1068', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (191, 'Принтер Epson 6200 L', '101041-133', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (192, 'Монитор BenQ Q7T4', '101041-7', null, null);
INSERT INTO Inventory (ID, Name, inventory_number, additional_code, id_equipment) VALUES (193, 'Сканер ScanMaker 3830', '1040600904', null, null);